# Generated by Django 4.0.4 on 2022-06-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classOfBusiness_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('classOfBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.classofbusiness')),
            ],
        ),
    ]
