# Generated by Django 4.0.4 on 2022-07-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='votes',
        ),
        migrations.AlterField(
            model_name='department',
            name='classOfBusiness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.classofbusiness'),
        ),
    ]
